"""
This type stub file was generated by pyright.
"""

import os
import sys
import shlex
from . import _MeCab

__all__ = _reexport_filtered(__import__(__name__), _MeCab)
VERSION = ...
def try_import_unidic(): # -> str | None:
    """Import unidic or unidic-lite if available. Return dicdir.

    This is specifically for dictionaries installed via pip.
    """
    ...

FAILMESSAGE = ...
def get_error_details(args): # -> str:
    """Instantiate a Model to get output from MeCab.

    Due to an upstream bug, errors in Tagger intialization don't give useful
    error output."""
    ...

def error_info(args): # -> str:
    """Render guide to solving initialization errors."""
    ...

class Tagger(_MeCab.Tagger):
    def __init__(self, rawargs=...) -> None:
        ...
    


class Model(_MeCab.Model):
    def __init__(self, rawargs=..., error_check=...) -> None:
        ...
    


