"""
This type stub file was generated by pyright.
"""

def parse(): # -> None:
    """Parse input from stdin.

    This is a simple wrapper for mecab-python3 so you can test it from the
    command line.  Like the mecab binary, it treats each line of stdin as one
    sentence. You can pass tagger arguments here too.
    """
    ...

def info(): # -> None:
    """Print configuration info."""
    ...

