"""
This type stub file was generated by pyright.
"""

from whoosh.analysis import Tokenizer

STOP_WORDS = ...
accepted_chars = ...
class ChineseTokenizer(Tokenizer):
    def __call__(self, text, **kargs): # -> Generator[Any, Any, None]:
        ...
    


def ChineseAnalyzer(stoplist=..., minsize=..., stemfn=..., cachesize=...):
    ...

