"""
This type stub file was generated by pyright.
"""

from .tfidf import KeywordExtractor
from .._compat import *

class UndirectWeightedGraph:
    d = ...
    def __init__(self) -> None:
        ...
    
    def addEdge(self, start, end, weight): # -> None:
        ...
    
    def rank(self): # -> defaultdict[Any, float]:
        ...
    


class TextRank(KeywordExtractor):
    def __init__(self) -> None:
        ...
    
    def pairfilter(self, wp): # -> bool:
        ...
    
    def textrank(self, sentence, topK=..., withWeight=..., allowPOS=..., withFlag=...): # -> list[tuple[Any, float]] | list[Any]:
        """
        Extract keywords from sentence using TextRank algorithm.
        Parameter:
            - topK: return how many top keywords. `None` for all possible words.
            - withWeight: if True, return a list of (word, weight);
                          if False, return a list of words.
            - allowPOS: the allowed POS list eg. ['ns', 'n', 'vn', 'v'].
                        if the POS of w is not in this list, it will be filtered.
            - withFlag: if True, return a list of pair(word, weight) like posseg.cut
                        if False, return a list of words
        """
        ...
    
    extract_tags = ...


