"""
This type stub file was generated by pyright.
"""

"""
Define the function to create lexical analysis model and model's data reader
"""
def create_model(vocab_size, num_labels, mode=...): # -> dict[str, list[Any] | Any]:
    """create lac model"""
    ...

