"""
This type stub file was generated by pyright.
"""

"""
The function lex_net(args) define the lexical analysis network structure
"""
def lex_net(word, vocab_size, num_labels, for_infer=..., target=...):
    """
    define the lexical analysis network structure
    word: stores the input of the model
    for_infer: a boolean value, indicating if the model to be created is for training or predicting.

    return:
        for infer: return the prediction
        otherwise: return the prediction
    """
    ...

