"""
This type stub file was generated by pyright.
"""

"""
The file_reader converts raw corpus to input.
"""
def load_kv_dict(dict_path, reverse=..., delimiter=..., key_func=..., value_func=...): # -> dict[Any, Any]:
    """
    Load key-value dict from file
    """
    ...

class Dataset:
    """data reader"""
    def __init__(self) -> None:
        ...
    
    @property
    def vocab_size(self):
        """vocabulary size"""
        ...
    
    @property
    def num_labels(self):
        """num_labels"""
        ...
    
    def word_to_ids(self, words): # -> list[Any]:
        """convert word to word index"""
        ...
    
    def label_to_ids(self, labels): # -> list[Any]:
        """convert label to label index"""
        ...
    
    def get_vars(self, str1): # -> list[Any]:
        ...
    


