"""
This type stub file was generated by pyright.
"""

"""
util tools
"""
def str2bool(v): # -> bool:
    """
    argparse does not support True or False in python
    """
    ...

def parse_result(words, crf_decode, dataset): # -> tuple[Any | list[Any], Any | list[Any]]:
    """ parse result """
    ...

def parse_padding_result(words, crf_decode, seq_lens, dataset): # -> list[Any]:
    """ parse padding result """
    ...

def init_checkpoint(exe, init_checkpoint_path, main_program): # -> None:
    """
    Init CheckPoint
    """
    ...

